// This file is generated by `scripts/generate-site-icons.mjs`. Do not edit by hand.

const icon_FaAmazon_ff9900 = new URL("../assets/site-icons/FaAmazon-ff9900.svg", import.meta.url).toString()
const icon_FaApple_000000 = new URL("../assets/site-icons/FaApple-000000.svg", import.meta.url).toString()
const icon_FaAws_ff9900 = new URL("../assets/site-icons/FaAws-ff9900.svg", import.meta.url).toString()
const icon_FaBehance_1769ff = new URL("../assets/site-icons/FaBehance-1769ff.svg", import.meta.url).toString()
const icon_FaBitbucket_0052cc = new URL("../assets/site-icons/FaBitbucket-0052cc.svg", import.meta.url).toString()
const icon_FaCodepen_000000 = new URL("../assets/site-icons/FaCodepen-000000.svg", import.meta.url).toString()
const icon_FaDiscord_5865f2 = new URL("../assets/site-icons/FaDiscord-5865f2.svg", import.meta.url).toString()
const icon_FaDocker_2496ed = new URL("../assets/site-icons/FaDocker-2496ed.svg", import.meta.url).toString()
const icon_FaDribbble_ea4c89 = new URL("../assets/site-icons/FaDribbble-ea4c89.svg", import.meta.url).toString()
const icon_FaDropbox_0061ff = new URL("../assets/site-icons/FaDropbox-0061ff.svg", import.meta.url).toString()
const icon_FaFacebookF_1877f2 = new URL("../assets/site-icons/FaFacebookF-1877f2.svg", import.meta.url).toString()
const icon_FaFigma_f24e1e = new URL("../assets/site-icons/FaFigma-f24e1e.svg", import.meta.url).toString()
const icon_FaGithub_181717 = new URL("../assets/site-icons/FaGithub-181717.svg", import.meta.url).toString()
const icon_FaGitlab_fc6d26 = new URL("../assets/site-icons/FaGitlab-fc6d26.svg", import.meta.url).toString()
const icon_FaHackerNews_ff6600 = new URL("../assets/site-icons/FaHackerNews-ff6600.svg", import.meta.url).toString()
const icon_FaInstagram_e4405f = new URL("../assets/site-icons/FaInstagram-e4405f.svg", import.meta.url).toString()
const icon_FaLinkedinIn_0a66c2 = new URL("../assets/site-icons/FaLinkedinIn-0a66c2.svg", import.meta.url).toString()
const icon_FaMedium_000000 = new URL("../assets/site-icons/FaMedium-000000.svg", import.meta.url).toString()
const icon_FaMicrosoft_00a4ef = new URL("../assets/site-icons/FaMicrosoft-00a4ef.svg", import.meta.url).toString()
const icon_FaNpm_cb3837 = new URL("../assets/site-icons/FaNpm-cb3837.svg", import.meta.url).toString()
const icon_FaPaypal_003087 = new URL("../assets/site-icons/FaPaypal-003087.svg", import.meta.url).toString()
const icon_FaPinterestP_bd081c = new URL("../assets/site-icons/FaPinterestP-bd081c.svg", import.meta.url).toString()
const icon_FaPlaystation_003791 = new URL("../assets/site-icons/FaPlaystation-003791.svg", import.meta.url).toString()
const icon_FaRedditAlien_ff4500 = new URL("../assets/site-icons/FaRedditAlien-ff4500.svg", import.meta.url).toString()
const icon_FaSkype_00aff0 = new URL("../assets/site-icons/FaSkype-00aff0.svg", import.meta.url).toString()
const icon_FaSlack_4a154b = new URL("../assets/site-icons/FaSlack-4a154b.svg", import.meta.url).toString()
const icon_FaSnapchat_fffc00 = new URL("../assets/site-icons/FaSnapchat-fffc00.svg", import.meta.url).toString()
const icon_FaSoundcloud_ff5500 = new URL("../assets/site-icons/FaSoundcloud-ff5500.svg", import.meta.url).toString()
const icon_FaSpotify_1db954 = new URL("../assets/site-icons/FaSpotify-1db954.svg", import.meta.url).toString()
const icon_FaStackOverflow_f58025 = new URL("../assets/site-icons/FaStackOverflow-f58025.svg", import.meta.url).toString()
const icon_FaSteam_000000 = new URL("../assets/site-icons/FaSteam-000000.svg", import.meta.url).toString()
const icon_FaStripe_635bff = new URL("../assets/site-icons/FaStripe-635bff.svg", import.meta.url).toString()
const icon_FaTelegram_26a5e4 = new URL("../assets/site-icons/FaTelegram-26a5e4.svg", import.meta.url).toString()
const icon_FaTiktok_000000 = new URL("../assets/site-icons/FaTiktok-000000.svg", import.meta.url).toString()
const icon_FaTrello_0052cc = new URL("../assets/site-icons/FaTrello-0052cc.svg", import.meta.url).toString()
const icon_FaTumblr_36465d = new URL("../assets/site-icons/FaTumblr-36465d.svg", import.meta.url).toString()
const icon_FaTwitch_9146ff = new URL("../assets/site-icons/FaTwitch-9146ff.svg", import.meta.url).toString()
const icon_FaVimeoV_1ab7ea = new URL("../assets/site-icons/FaVimeoV-1ab7ea.svg", import.meta.url).toString()
const icon_FaWhatsapp_25d366 = new URL("../assets/site-icons/FaWhatsapp-25d366.svg", import.meta.url).toString()
const icon_FaWikipediaW_000000 = new URL("../assets/site-icons/FaWikipediaW-000000.svg", import.meta.url).toString()
const icon_FaXbox_107c10 = new URL("../assets/site-icons/FaXbox-107c10.svg", import.meta.url).toString()
const icon_FaXTwitter_1da1f2 = new URL("../assets/site-icons/FaXTwitter-1da1f2.svg", import.meta.url).toString()
const icon_FaYoutube_ff0000 = new URL("../assets/site-icons/FaYoutube-ff0000.svg", import.meta.url).toString()
const icon_Si1panel_005eeb = new URL("../assets/site-icons/Si1panel-005eeb.svg", import.meta.url).toString()
const icon_SiAdguardhome_68bc71 = new URL("../assets/site-icons/SiAdguardhome-68bc71.svg", import.meta.url).toString()
const icon_SiAdobe_ff0000 = new URL("../assets/site-icons/SiAdobe-ff0000.svg", import.meta.url).toString()
const icon_SiAirbnb_ff5a5f = new URL("../assets/site-icons/SiAirbnb-ff5a5f.svg", import.meta.url).toString()
const icon_SiAirtable_18bfff = new URL("../assets/site-icons/SiAirtable-18bfff.svg", import.meta.url).toString()
const icon_SiAlibabadotcom_ff6a00 = new URL("../assets/site-icons/SiAlibabadotcom-ff6a00.svg", import.meta.url).toString()
const icon_SiAliexpress_ff6a00 = new URL("../assets/site-icons/SiAliexpress-ff6a00.svg", import.meta.url).toString()
const icon_SiAmd_ed1c24 = new URL("../assets/site-icons/SiAmd-ed1c24.svg", import.meta.url).toString()
const icon_SiAnthropic_d4a27f = new URL("../assets/site-icons/SiAnthropic-d4a27f.svg", import.meta.url).toString()
const icon_SiApplemusic_fa243c = new URL("../assets/site-icons/SiApplemusic-fa243c.svg", import.meta.url).toString()
const icon_SiArchlinux_1793d1 = new URL("../assets/site-icons/SiArchlinux-1793d1.svg", import.meta.url).toString()
const icon_SiAsana_f06a6a = new URL("../assets/site-icons/SiAsana-f06a6a.svg", import.meta.url).toString()
const icon_SiBaidu_2319dc = new URL("../assets/site-icons/SiBaidu-2319dc.svg", import.meta.url).toString()
const icon_SiBandcamp_408294 = new URL("../assets/site-icons/SiBandcamp-408294.svg", import.meta.url).toString()
const icon_SiBilibili_00aeec = new URL("../assets/site-icons/SiBilibili-00aeec.svg", import.meta.url).toString()
const icon_SiBinance_f0b90b = new URL("../assets/site-icons/SiBinance-f0b90b.svg", import.meta.url).toString()
const icon_SiBox_0061d5 = new URL("../assets/site-icons/SiBox-0061d5.svg", import.meta.url).toString()
const icon_SiBytedance_000000 = new URL("../assets/site-icons/SiBytedance-000000.svg", import.meta.url).toString()
const icon_SiCanva_00c4cc = new URL("../assets/site-icons/SiCanva-00c4cc.svg", import.meta.url).toString()
const icon_SiCentos_262577 = new URL("../assets/site-icons/SiCentos-262577.svg", import.meta.url).toString()
const icon_SiClickup_7b68ee = new URL("../assets/site-icons/SiClickup-7b68ee.svg", import.meta.url).toString()
const icon_SiCloudflare_f38020 = new URL("../assets/site-icons/SiCloudflare-f38020.svg", import.meta.url).toString()
const icon_SiCloudimages_3498db = new URL("../assets/site-icons/SiCloudimages-3498db.svg", import.meta.url).toString()
const icon_SiCnn_cc0000 = new URL("../assets/site-icons/SiCnn-cc0000.svg", import.meta.url).toString()
const icon_SiCodecademy_1f4056 = new URL("../assets/site-icons/SiCodecademy-1f4056.svg", import.meta.url).toString()
const icon_SiCodesandbox_151515 = new URL("../assets/site-icons/SiCodesandbox-151515.svg", import.meta.url).toString()
const icon_SiCoinbase_0052ff = new URL("../assets/site-icons/SiCoinbase-0052ff.svg", import.meta.url).toString()
const icon_SiCoursera_0056d2 = new URL("../assets/site-icons/SiCoursera-0056d2.svg", import.meta.url).toString()
const icon_SiDebian_a81d33 = new URL("../assets/site-icons/SiDebian-a81d33.svg", import.meta.url).toString()
const icon_SiDevdotto_0a0a0a = new URL("../assets/site-icons/SiDevdotto-0a0a0a.svg", import.meta.url).toString()
const icon_SiDigitalocean_0080ff = new URL("../assets/site-icons/SiDigitalocean-0080ff.svg", import.meta.url).toString()
const icon_SiDoordash_ff3008 = new URL("../assets/site-icons/SiDoordash-ff3008.svg", import.meta.url).toString()
const icon_SiDuckduckgo_de5833 = new URL("../assets/site-icons/SiDuckduckgo-de5833.svg", import.meta.url).toString()
const icon_SiDuolingo_58cc02 = new URL("../assets/site-icons/SiDuolingo-58cc02.svg", import.meta.url).toString()
const icon_SiEa_000000 = new URL("../assets/site-icons/SiEa-000000.svg", import.meta.url).toString()
const icon_SiEbay_e53238 = new URL("../assets/site-icons/SiEbay-e53238.svg", import.meta.url).toString()
const icon_SiEcosia_3eb85f = new URL("../assets/site-icons/SiEcosia-3eb85f.svg", import.meta.url).toString()
const icon_SiEdx_02262b = new URL("../assets/site-icons/SiEdx-02262b.svg", import.meta.url).toString()
const icon_SiEpicgames_313131 = new URL("../assets/site-icons/SiEpicgames-313131.svg", import.meta.url).toString()
const icon_SiEtsy_f45800 = new URL("../assets/site-icons/SiEtsy-f45800.svg", import.meta.url).toString()
const icon_SiEvernote_00a82d = new URL("../assets/site-icons/SiEvernote-00a82d.svg", import.meta.url).toString()
const icon_SiFedora_51a2da = new URL("../assets/site-icons/SiFedora-51a2da.svg", import.meta.url).toString()
const icon_SiFirebase_ffca28 = new URL("../assets/site-icons/SiFirebase-ffca28.svg", import.meta.url).toString()
const icon_SiFramer_0055ff = new URL("../assets/site-icons/SiFramer-0055ff.svg", import.meta.url).toString()
const icon_SiFreecodecamp_0a0a23 = new URL("../assets/site-icons/SiFreecodecamp-0a0a23.svg", import.meta.url).toString()
const icon_SiFreshrss_0061be = new URL("../assets/site-icons/SiFreshrss-0061be.svg", import.meta.url).toString()
const icon_SiGmail_ea4335 = new URL("../assets/site-icons/SiGmail-ea4335.svg", import.meta.url).toString()
const icon_SiGoodreads_553b08 = new URL("../assets/site-icons/SiGoodreads-553b08.svg", import.meta.url).toString()
const icon_SiGooglecalendar_4285f4 = new URL("../assets/site-icons/SiGooglecalendar-4285f4.svg", import.meta.url).toString()
const icon_SiGooglecloud_4285f4 = new URL("../assets/site-icons/SiGooglecloud-4285f4.svg", import.meta.url).toString()
const icon_SiGooglecolab_f9ab00 = new URL("../assets/site-icons/SiGooglecolab-f9ab00.svg", import.meta.url).toString()
const icon_SiGoogledocs_4285f4 = new URL("../assets/site-icons/SiGoogledocs-4285f4.svg", import.meta.url).toString()
const icon_SiGoogledrive_4285f4 = new URL("../assets/site-icons/SiGoogledrive-4285f4.svg", import.meta.url).toString()
const icon_SiGooglegemini_8e75b2 = new URL("../assets/site-icons/SiGooglegemini-8e75b2.svg", import.meta.url).toString()
const icon_SiGooglemaps_4285f4 = new URL("../assets/site-icons/SiGooglemaps-4285f4.svg", import.meta.url).toString()
const icon_SiGooglemeet_00897b = new URL("../assets/site-icons/SiGooglemeet-00897b.svg", import.meta.url).toString()
const icon_SiGooglephotos_4285f4 = new URL("../assets/site-icons/SiGooglephotos-4285f4.svg", import.meta.url).toString()
const icon_SiGoogleplay_414141 = new URL("../assets/site-icons/SiGoogleplay-414141.svg", import.meta.url).toString()
const icon_SiGooglesheets_34a853 = new URL("../assets/site-icons/SiGooglesheets-34a853.svg", import.meta.url).toString()
const icon_SiGoogleslides_fbbc04 = new URL("../assets/site-icons/SiGoogleslides-fbbc04.svg", import.meta.url).toString()
const icon_SiGoogletranslate_4285f4 = new URL("../assets/site-icons/SiGoogletranslate-4285f4.svg", import.meta.url).toString()
const icon_SiGrubhub_f63440 = new URL("../assets/site-icons/SiGrubhub-f63440.svg", import.meta.url).toString()
const icon_SiHackerrank_00ea64 = new URL("../assets/site-icons/SiHackerrank-00ea64.svg", import.meta.url).toString()
const icon_SiHashnode_2962ff = new URL("../assets/site-icons/SiHashnode-2962ff.svg", import.meta.url).toString()
const icon_SiHbo_000000 = new URL("../assets/site-icons/SiHbo-000000.svg", import.meta.url).toString()
const icon_SiHeroku_430098 = new URL("../assets/site-icons/SiHeroku-430098.svg", import.meta.url).toString()
const icon_SiHexo_0e83cd = new URL("../assets/site-icons/SiHexo-0e83cd.svg", import.meta.url).toString()
const icon_SiHuggingface_ffd21e = new URL("../assets/site-icons/SiHuggingface-ffd21e.svg", import.meta.url).toString()
const icon_SiHuya_ffa900 = new URL("../assets/site-icons/SiHuya-ffa900.svg", import.meta.url).toString()
const icon_SiIcloud_3693f3 = new URL("../assets/site-icons/SiIcloud-3693f3.svg", import.meta.url).toString()
const icon_SiImdb_f5c518 = new URL("../assets/site-icons/SiImdb-f5c518.svg", import.meta.url).toString()
const icon_SiIntel_0071c5 = new URL("../assets/site-icons/SiIntel-0071c5.svg", import.meta.url).toString()
const icon_SiInternetarchive_000000 = new URL("../assets/site-icons/SiInternetarchive-000000.svg", import.meta.url).toString()
const icon_SiInvision_ff3366 = new URL("../assets/site-icons/SiInvision-ff3366.svg", import.meta.url).toString()
const icon_SiItchdotio_fa5c5c = new URL("../assets/site-icons/SiItchdotio-fa5c5c.svg", import.meta.url).toString()
const icon_SiIthome_d22322 = new URL("../assets/site-icons/SiIthome-d22322.svg", import.meta.url).toString()
const icon_SiIttools_10b981 = new URL("../assets/site-icons/SiIttools-10b981.svg", import.meta.url).toString()
const icon_SiJellyfin_00a4dc = new URL("../assets/site-icons/SiJellyfin-00a4dc.svg", import.meta.url).toString()
const icon_SiJsfiddle_0084ff = new URL("../assets/site-icons/SiJsfiddle-0084ff.svg", import.meta.url).toString()
const icon_SiKaggle_20beff = new URL("../assets/site-icons/SiKaggle-20beff.svg", import.meta.url).toString()
const icon_SiKhanacademy_14bf96 = new URL("../assets/site-icons/SiKhanacademy-14bf96.svg", import.meta.url).toString()
const icon_SiKubernetes_326ce5 = new URL("../assets/site-icons/SiKubernetes-326ce5.svg", import.meta.url).toString()
const icon_SiLastdotfm_d51007 = new URL("../assets/site-icons/SiLastdotfm-d51007.svg", import.meta.url).toString()
const icon_SiLeetcode_ffa116 = new URL("../assets/site-icons/SiLeetcode-ffa116.svg", import.meta.url).toString()
const icon_SiLinear_5e6ad2 = new URL("../assets/site-icons/SiLinear-5e6ad2.svg", import.meta.url).toString()
const icon_SiLinux_fcc624 = new URL("../assets/site-icons/SiLinux-fcc624.svg", import.meta.url).toString()
const icon_SiLinuxdo_ffb003 = new URL("../assets/site-icons/SiLinuxdo-ffb003.svg", import.meta.url).toString()
const icon_SiLinuxmint_87cf3e = new URL("../assets/site-icons/SiLinuxmint-87cf3e.svg", import.meta.url).toString()
const icon_SiLyft_ff00bf = new URL("../assets/site-icons/SiLyft-ff00bf.svg", import.meta.url).toString()
const icon_SiMail_ea4335 = new URL("../assets/site-icons/SiMail-ea4335.svg", import.meta.url).toString()
const icon_SiManjaro_35bf5c = new URL("../assets/site-icons/SiManjaro-35bf5c.svg", import.meta.url).toString()
const icon_SiMarkdown_737373 = new URL("../assets/site-icons/SiMarkdown-737373.svg", import.meta.url).toString()
const icon_SiMastodon_6364ff = new URL("../assets/site-icons/SiMastodon-6364ff.svg", import.meta.url).toString()
const icon_SiMega_d90007 = new URL("../assets/site-icons/SiMega-d90007.svg", import.meta.url).toString()
const icon_SiMikanani_fda143 = new URL("../assets/site-icons/SiMikanani-fda143.svg", import.meta.url).toString()
const icon_SiMiro_ffd02f = new URL("../assets/site-icons/SiMiro-ffd02f.svg", import.meta.url).toString()
const icon_SiMongodb_47a248 = new URL("../assets/site-icons/SiMongodb-47a248.svg", import.meta.url).toString()
const icon_SiNastool_2196f3 = new URL("../assets/site-icons/SiNastool-2196f3.svg", import.meta.url).toString()
const icon_SiNeteasecloudmusic_c20c0c = new URL("../assets/site-icons/SiNeteasecloudmusic-c20c0c.svg", import.meta.url).toString()
const icon_SiNetflix_e50914 = new URL("../assets/site-icons/SiNetflix-e50914.svg", import.meta.url).toString()
const icon_SiNetlify_00c7b7 = new URL("../assets/site-icons/SiNetlify-00c7b7.svg", import.meta.url).toString()
const icon_SiNewyorktimes_000000 = new URL("../assets/site-icons/SiNewyorktimes-000000.svg", import.meta.url).toString()
const icon_SiNintendo_e60012 = new URL("../assets/site-icons/SiNintendo-e60012.svg", import.meta.url).toString()
const icon_SiNotion_000000 = new URL("../assets/site-icons/SiNotion-000000.svg", import.meta.url).toString()
const icon_SiNvidia_76b900 = new URL("../assets/site-icons/SiNvidia-76b900.svg", import.meta.url).toString()
const icon_SiObsidian_7c3aed = new URL("../assets/site-icons/SiObsidian-7c3aed.svg", import.meta.url).toString()
const icon_SiOpenai_412991 = new URL("../assets/site-icons/SiOpenai-412991.svg", import.meta.url).toString()
const icon_SiOpensuse_73ba25 = new URL("../assets/site-icons/SiOpensuse-73ba25.svg", import.meta.url).toString()
const icon_SiOpenwrt_00b5e2 = new URL("../assets/site-icons/SiOpenwrt-00b5e2.svg", import.meta.url).toString()
const icon_SiOracle_f80000 = new URL("../assets/site-icons/SiOracle-f80000.svg", import.meta.url).toString()
const icon_SiPerplexity_1fb8cd = new URL("../assets/site-icons/SiPerplexity-1fb8cd.svg", import.meta.url).toString()
const icon_SiPluralsight_ec008c = new URL("../assets/site-icons/SiPluralsight-ec008c.svg", import.meta.url).toString()
const icon_SiPoe_5c46f5 = new URL("../assets/site-icons/SiPoe-5c46f5.svg", import.meta.url).toString()
const icon_SiPostgresql_4169e1 = new URL("../assets/site-icons/SiPostgresql-4169e1.svg", import.meta.url).toString()
const icon_SiPrimevideo_00a8e1 = new URL("../assets/site-icons/SiPrimevideo-00a8e1.svg", import.meta.url).toString()
const icon_SiProducthunt_da552f = new URL("../assets/site-icons/SiProducthunt-da552f.svg", import.meta.url).toString()
const icon_SiProxmox_e57000 = new URL("../assets/site-icons/SiProxmox-e57000.svg", import.meta.url).toString()
const icon_SiQbittorrent_2f67ba = new URL("../assets/site-icons/SiQbittorrent-2f67ba.svg", import.meta.url).toString()
const icon_SiRailway_0b0d0e = new URL("../assets/site-icons/SiRailway-0b0d0e.svg", import.meta.url).toString()
const icon_SiReader_0084ff = new URL("../assets/site-icons/SiReader-0084ff.svg", import.meta.url).toString()
const icon_SiRedhat_ee0000 = new URL("../assets/site-icons/SiRedhat-ee0000.svg", import.meta.url).toString()
const icon_SiRedis_dc382d = new URL("../assets/site-icons/SiRedis-dc382d.svg", import.meta.url).toString()
const icon_SiReplit_f26207 = new URL("../assets/site-icons/SiReplit-f26207.svg", import.meta.url).toString()
const icon_SiRevolut_0075eb = new URL("../assets/site-icons/SiRevolut-0075eb.svg", import.meta.url).toString()
const icon_SiRobinhood_00c805 = new URL("../assets/site-icons/SiRobinhood-00c805.svg", import.meta.url).toString()
const icon_SiRoblox_000000 = new URL("../assets/site-icons/SiRoblox-000000.svg", import.meta.url).toString()
const icon_SiRottentomatoes_fa320a = new URL("../assets/site-icons/SiRottentomatoes-fa320a.svg", import.meta.url).toString()
const icon_SiRss_ff6600 = new URL("../assets/site-icons/SiRss-ff6600.svg", import.meta.url).toString()
const icon_SiSafeline_79ba49 = new URL("../assets/site-icons/SiSafeline-79ba49.svg", import.meta.url).toString()
const icon_SiSalesforce_00a1e0 = new URL("../assets/site-icons/SiSalesforce-00a1e0.svg", import.meta.url).toString()
const icon_SiShopify_7ab55c = new URL("../assets/site-icons/SiShopify-7ab55c.svg", import.meta.url).toString()
const icon_SiSignal_3a76f0 = new URL("../assets/site-icons/SiSignal-3a76f0.svg", import.meta.url).toString()
const icon_SiSinaweibo_e6162d = new URL("../assets/site-icons/SiSinaweibo-e6162d.svg", import.meta.url).toString()
const icon_SiSketch_f7b500 = new URL("../assets/site-icons/SiSketch-f7b500.svg", import.meta.url).toString()
const icon_SiSkillshare_00ff84 = new URL("../assets/site-icons/SiSkillshare-00ff84.svg", import.meta.url).toString()
const icon_SiSubstack_ff6719 = new URL("../assets/site-icons/SiSubstack-ff6719.svg", import.meta.url).toString()
const icon_SiSupabase_3ecf8e = new URL("../assets/site-icons/SiSupabase-3ecf8e.svg", import.meta.url).toString()
const icon_SiSynology_b5b5b6 = new URL("../assets/site-icons/SiSynology-b5b5b6.svg", import.meta.url).toString()
const icon_SiTaobao_ff6a00 = new URL("../assets/site-icons/SiTaobao-ff6a00.svg", import.meta.url).toString()
const icon_SiTarget_cc0000 = new URL("../assets/site-icons/SiTarget-cc0000.svg", import.meta.url).toString()
const icon_SiTechcrunch_029e74 = new URL("../assets/site-icons/SiTechcrunch-029e74.svg", import.meta.url).toString()
const icon_SiTencentqq_eb1923 = new URL("../assets/site-icons/SiTencentqq-eb1923.svg", import.meta.url).toString()
const icon_SiTheguardian_052962 = new URL("../assets/site-icons/SiTheguardian-052962.svg", import.meta.url).toString()
const icon_SiThreads_000000 = new URL("../assets/site-icons/SiThreads-000000.svg", import.meta.url).toString()
const icon_SiTidal_000000 = new URL("../assets/site-icons/SiTidal-000000.svg", import.meta.url).toString()
const icon_SiTiktok_000000 = new URL("../assets/site-icons/SiTiktok-000000.svg", import.meta.url).toString()
const icon_SiTodoist_e44332 = new URL("../assets/site-icons/SiTodoist-e44332.svg", import.meta.url).toString()
const icon_SiTophub_ff5722 = new URL("../assets/site-icons/SiTophub-ff5722.svg", import.meta.url).toString()
const icon_SiTrilium_6eaa5e = new URL("../assets/site-icons/SiTrilium-6eaa5e.svg", import.meta.url).toString()
const icon_SiTripadvisor_34e0a1 = new URL("../assets/site-icons/SiTripadvisor-34e0a1.svg", import.meta.url).toString()
const icon_SiUber_000000 = new URL("../assets/site-icons/SiUber-000000.svg", import.meta.url).toString()
const icon_SiUbisoft_000000 = new URL("../assets/site-icons/SiUbisoft-000000.svg", import.meta.url).toString()
const icon_SiUbuntu_e95420 = new URL("../assets/site-icons/SiUbuntu-e95420.svg", import.meta.url).toString()
const icon_SiUdemy_a435f0 = new URL("../assets/site-icons/SiUdemy-a435f0.svg", import.meta.url).toString()
const icon_SiUptimekuma_5cdd8b = new URL("../assets/site-icons/SiUptimekuma-5cdd8b.svg", import.meta.url).toString()
const icon_SiV2Ex_1f73b7 = new URL("../assets/site-icons/SiV2Ex-1f73b7.svg", import.meta.url).toString()
const icon_SiVercel_000000 = new URL("../assets/site-icons/SiVercel-000000.svg", import.meta.url).toString()
const icon_SiWalmart_0071dc = new URL("../assets/site-icons/SiWalmart-0071dc.svg", import.meta.url).toString()
const icon_SiWechat_07c160 = new URL("../assets/site-icons/SiWechat-07c160.svg", import.meta.url).toString()
const icon_SiWise_9fe870 = new URL("../assets/site-icons/SiWise-9fe870.svg", import.meta.url).toString()
const icon_SiXiaohongshu_ff2442 = new URL("../assets/site-icons/SiXiaohongshu-ff2442.svg", import.meta.url).toString()
const icon_SiYelp_d32323 = new URL("../assets/site-icons/SiYelp-d32323.svg", import.meta.url).toString()
const icon_SiYoutubemusic_ff0000 = new URL("../assets/site-icons/SiYoutubemusic-ff0000.svg", import.meta.url).toString()
const icon_SiZhihu_0084ff = new URL("../assets/site-icons/SiZhihu-0084ff.svg", import.meta.url).toString()
const icon_SiZoom_2d8cff = new URL("../assets/site-icons/SiZoom-2d8cff.svg", import.meta.url).toString()

export const ICON_URL_MAP: Record<string, string> = {
  "163.com": icon_SiNeteasecloudmusic_c20c0c,
  "192.168.88.1": icon_SiOpenwrt_00b5e2,
  "adobe.com": icon_SiAdobe_ff0000,
  "airbnb.com": icon_SiAirbnb_ff5a5f,
  "airtable.com": icon_SiAirtable_18bfff,
  "aliexpress.com": icon_SiAliexpress_ff6a00,
  "aliyun.com": icon_SiAlibabadotcom_ff6a00,
  "amazon.com": icon_FaAmazon_ff9900,
  "amd.com": icon_SiAmd_ed1c24,
  "anthropic.com": icon_SiAnthropic_d4a27f,
  "apple.com": icon_FaApple_000000,
  "archive.org": icon_SiInternetarchive_000000,
  "archlinux.org": icon_SiArchlinux_1793d1,
  "asana.com": icon_SiAsana_f06a6a,
  "aws.amazon.com": icon_FaAws_ff9900,
  "baidu.com": icon_SiBaidu_2319dc,
  "bandcamp.com": icon_SiBandcamp_408294,
  "bard.google.com": icon_SiGooglegemini_8e75b2,
  "behance.net": icon_FaBehance_1769ff,
  "bilibili.com": icon_SiBilibili_00aeec,
  "binance.com": icon_SiBinance_f0b90b,
  "bitbucket.org": icon_FaBitbucket_0052cc,
  "box.com": icon_SiBox_0061d5,
  "bytedance.com": icon_SiBytedance_000000,
  "calendar.google.com": icon_SiGooglecalendar_4285f4,
  "canva.com": icon_SiCanva_00c4cc,
  "centos.org": icon_SiCentos_262577,
  "chat.openai.com": icon_SiOpenai_412991,
  "chatgpt.com": icon_SiOpenai_412991,
  "claude.ai": icon_SiAnthropic_d4a27f,
  "clickup.com": icon_SiClickup_7b68ee,
  "cloud.google.com": icon_SiGooglecloud_4285f4,
  "cloudflare.com": icon_SiCloudflare_f38020,
  "cnn.com": icon_SiCnn_cc0000,
  "codecademy.com": icon_SiCodecademy_1f4056,
  "codepen.io": icon_FaCodepen_000000,
  "codesandbox.io": icon_SiCodesandbox_151515,
  "coinbase.com": icon_SiCoinbase_0052ff,
  "colab.research.google.com": icon_SiGooglecolab_f9ab00,
  "coursera.org": icon_SiCoursera_0056d2,
  "dash.cloudflare.com": icon_SiCloudflare_f38020,
  "debian.org": icon_SiDebian_a81d33,
  "dev.to": icon_SiDevdotto_0a0a0a,
  "digitalocean.com": icon_SiDigitalocean_0080ff,
  "discord.com": icon_FaDiscord_5865f2,
  "docker.com": icon_FaDocker_2496ed,
  "docs.google.com": icon_SiGoogledocs_4285f4,
  "doordash.com": icon_SiDoordash_ff3008,
  "douyin.com": icon_SiTiktok_000000,
  "dribbble.com": icon_FaDribbble_ea4c89,
  "drive.google.com": icon_SiGoogledrive_4285f4,
  "dropbox.com": icon_FaDropbox_0061ff,
  "duckduckgo.com": icon_SiDuckduckgo_de5833,
  "duolingo.com": icon_SiDuolingo_58cc02,
  "ea.com": icon_SiEa_000000,
  "ebay.com": icon_SiEbay_e53238,
  "ecosia.org": icon_SiEcosia_3eb85f,
  "edx.org": icon_SiEdx_02262b,
  "epicgames.com": icon_SiEpicgames_313131,
  "etsy.com": icon_SiEtsy_f45800,
  "evernote.com": icon_SiEvernote_00a82d,
  "facebook.com": icon_FaFacebookF_1877f2,
  "fedoraproject.org": icon_SiFedora_51a2da,
  "figma.com": icon_FaFigma_f24e1e,
  "firebase.google.com": icon_SiFirebase_ffca28,
  "framer.com": icon_SiFramer_0055ff,
  "freecodecamp.org": icon_SiFreecodecamp_0a0a23,
  "gemini.google.com": icon_SiGooglegemini_8e75b2,
  "github.com": icon_FaGithub_181717,
  "gitlab.com": icon_FaGitlab_fc6d26,
  "gmail.com": icon_SiGmail_ea4335,
  "goodreads.com": icon_SiGoodreads_553b08,
  "grubhub.com": icon_SiGrubhub_f63440,
  "hackerrank.com": icon_SiHackerrank_00ea64,
  "hashnode.com": icon_SiHashnode_2962ff,
  "hbomax.com": icon_SiHbo_000000,
  "heroku.com": icon_SiHeroku_430098,
  "hub.docker.com": icon_FaDocker_2496ed,
  "huggingface.co": icon_SiHuggingface_ffd21e,
  "huya.com": icon_SiHuya_ffa900,
  "icloud.com": icon_SiIcloud_3693f3,
  "imdb.com": icon_SiImdb_f5c518,
  "instagram.com": icon_FaInstagram_e4405f,
  "intel.com": icon_SiIntel_0071c5,
  "invisionapp.com": icon_SiInvision_ff3366,
  "itch.io": icon_SiItchdotio_fa5c5c,
  "ithome.com": icon_SiIthome_d22322,
  "jsfiddle.net": icon_SiJsfiddle_0084ff,
  "kaggle.com": icon_SiKaggle_20beff,
  "khanacademy.org": icon_SiKhanacademy_14bf96,
  "kubernetes.io": icon_SiKubernetes_326ce5,
  "last.fm": icon_SiLastdotfm_d51007,
  "leetcode.com": icon_SiLeetcode_ffa116,
  "linear.app": icon_SiLinear_5e6ad2,
  "linkedin.com": icon_FaLinkedinIn_0a66c2,
  "linux.do": icon_SiLinuxdo_ffb003,
  "linux.org": icon_SiLinux_fcc624,
  "linuxmint.com": icon_SiLinuxmint_87cf3e,
  "lyft.com": icon_SiLyft_ff00bf,
  "mail.google.com": icon_SiGmail_ea4335,
  "manjaro.org": icon_SiManjaro_35bf5c,
  "maps.google.com": icon_SiGooglemaps_4285f4,
  "mastodon.social": icon_SiMastodon_6364ff,
  "medium.com": icon_FaMedium_000000,
  "meet.google.com": icon_SiGooglemeet_00897b,
  "mega.nz": icon_SiMega_d90007,
  "microsoft.com": icon_FaMicrosoft_00a4ef,
  "mikanani.me": icon_SiMikanani_fda143,
  "miro.com": icon_SiMiro_ffd02f,
  "mongodb.com": icon_SiMongodb_47a248,
  "music.163.com": icon_SiNeteasecloudmusic_c20c0c,
  "music.apple.com": icon_SiApplemusic_fa243c,
  "music.youtube.com": icon_SiYoutubemusic_ff0000,
  "netflix.com": icon_SiNetflix_e50914,
  "netlify.com": icon_SiNetlify_00c7b7,
  "news.ycombinator.com": icon_FaHackerNews_ff6600,
  "nintendo.com": icon_SiNintendo_e60012,
  "notion.com": icon_SiNotion_000000,
  "notion.so": icon_SiNotion_000000,
  "npm.com": icon_FaNpm_cb3837,
  "npmjs.com": icon_FaNpm_cb3837,
  "nvidia.com": icon_SiNvidia_76b900,
  "nytimes.com": icon_SiNewyorktimes_000000,
  "obsidian.md": icon_SiObsidian_7c3aed,
  "open.spotify.com": icon_FaSpotify_1db954,
  "openai.com": icon_SiOpenai_412991,
  "opensuse.org": icon_SiOpensuse_73ba25,
  "oracle.com": icon_SiOracle_f80000,
  "paypal.com": icon_FaPaypal_003087,
  "perplexity.ai": icon_SiPerplexity_1fb8cd,
  "photos.google.com": icon_SiGooglephotos_4285f4,
  "pinterest.com": icon_FaPinterestP_bd081c,
  "play.google.com": icon_SiGoogleplay_414141,
  "playstation.com": icon_FaPlaystation_003791,
  "pluralsight.com": icon_SiPluralsight_ec008c,
  "poe.com": icon_SiPoe_5c46f5,
  "postgresql.org": icon_SiPostgresql_4169e1,
  "primevideo.com": icon_SiPrimevideo_00a8e1,
  "producthunt.com": icon_SiProducthunt_da552f,
  "qq.com": icon_SiTencentqq_eb1923,
  "railway.app": icon_SiRailway_0b0d0e,
  "reddit.com": icon_FaRedditAlien_ff4500,
  "redhat.com": icon_SiRedhat_ee0000,
  "redis.io": icon_SiRedis_dc382d,
  "replit.com": icon_SiReplit_f26207,
  "revolut.com": icon_SiRevolut_0075eb,
  "robinhood.com": icon_SiRobinhood_00c805,
  "roblox.com": icon_SiRoblox_000000,
  "rottentomatoes.com": icon_SiRottentomatoes_fa320a,
  "salesforce.com": icon_SiSalesforce_00a1e0,
  "sheets.google.com": icon_SiGooglesheets_34a853,
  "shopify.com": icon_SiShopify_7ab55c,
  "signal.org": icon_SiSignal_3a76f0,
  "sketch.com": icon_SiSketch_f7b500,
  "skillshare.com": icon_SiSkillshare_00ff84,
  "skype.com": icon_FaSkype_00aff0,
  "slack.com": icon_FaSlack_4a154b,
  "slides.google.com": icon_SiGoogleslides_fbbc04,
  "snapchat.com": icon_FaSnapchat_fffc00,
  "soundcloud.com": icon_FaSoundcloud_ff5500,
  "spotify.com": icon_FaSpotify_1db954,
  "stackoverflow.com": icon_FaStackOverflow_f58025,
  "steam.com": icon_FaSteam_000000,
  "store.steampowered.com": icon_FaSteam_000000,
  "stripe.com": icon_FaStripe_635bff,
  "substack.com": icon_SiSubstack_ff6719,
  "supabase.com": icon_SiSupabase_3ecf8e,
  "taobao.com": icon_SiTaobao_ff6a00,
  "target.com": icon_SiTarget_cc0000,
  "techcrunch.com": icon_SiTechcrunch_029e74,
  "telegram.org": icon_FaTelegram_26a5e4,
  "theguardian.com": icon_SiTheguardian_052962,
  "threads.net": icon_SiThreads_000000,
  "tidal.com": icon_SiTidal_000000,
  "tiktok.com": icon_FaTiktok_000000,
  "todoist.com": icon_SiTodoist_e44332,
  "tophub.today": icon_SiTophub_ff5722,
  "translate.google.com": icon_SiGoogletranslate_4285f4,
  "trello.com": icon_FaTrello_0052cc,
  "tripadvisor.com": icon_SiTripadvisor_34e0a1,
  "tumblr.com": icon_FaTumblr_36465d,
  "twitch.tv": icon_FaTwitch_9146ff,
  "twitter.com": icon_FaXTwitter_1da1f2,
  "uber.com": icon_SiUber_000000,
  "ubisoft.com": icon_SiUbisoft_000000,
  "ubuntu.com": icon_SiUbuntu_e95420,
  "udemy.com": icon_SiUdemy_a435f0,
  "v2ex.com": icon_SiV2Ex_1f73b7,
  "vercel.com": icon_SiVercel_000000,
  "vimeo.com": icon_FaVimeoV_1ab7ea,
  "walmart.com": icon_SiWalmart_0071dc,
  "web.telegram.org": icon_FaTelegram_26a5e4,
  "web.whatsapp.com": icon_FaWhatsapp_25d366,
  "wechat.com": icon_SiWechat_07c160,
  "weibo.com": icon_SiSinaweibo_e6162d,
  "weixin.qq.com": icon_SiWechat_07c160,
  "whatsapp.com": icon_FaWhatsapp_25d366,
  "wikipedia.org": icon_FaWikipediaW_000000,
  "wise.com": icon_SiWise_9fe870,
  "x.com": icon_FaXTwitter_1da1f2,
  "xbox.com": icon_FaXbox_107c10,
  "xiaohongshu.com": icon_SiXiaohongshu_ff2442,
  "yelp.com": icon_SiYelp_d32323,
  "youtube.com": icon_FaYoutube_ff0000,
  "zhihu.com": icon_SiZhihu_0084ff,
  "zoom.us": icon_SiZoom_2d8cff,
}

export const ICON_TITLE_MAP: Record<string, string> = {
  "1panel": icon_Si1panel_005eeb,
  "虎牙": icon_SiHuya_ffa900,
  "今日热榜": icon_SiTophub_ff5722,
  "雷池": icon_SiSafeline_79ba49,
  "蜜柑": icon_SiMikanani_fda143,
  "群晖": icon_SiSynology_b5b5b6,
  "图床": icon_SiCloudimages_3498db,
  "邮箱": icon_SiMail_ea4335,
  "阅读": icon_SiReader_0084ff,
  "adg": icon_SiAdguardhome_68bc71,
  "adguard": icon_SiAdguardhome_68bc71,
  "adguardhome": icon_SiAdguardhome_68bc71,
  "bt": icon_SiQbittorrent_2f67ba,
  "cloudflare": icon_SiCloudflare_f38020,
  "dsm": icon_SiSynology_b5b5b6,
  "freshrss": icon_SiFreshrss_0061be,
  "hexo": icon_SiHexo_0e83cd,
  "huya": icon_SiHuya_ffa900,
  "it tools": icon_SiIttools_10b981,
  "it之家": icon_SiIthome_d22322,
  "ithome": icon_SiIthome_d22322,
  "ittools": icon_SiIttools_10b981,
  "jellyfin": icon_SiJellyfin_00a4dc,
  "linux do": icon_SiLinuxdo_ffb003,
  "linuxdo": icon_SiLinuxdo_ffb003,
  "mail": icon_SiMail_ea4335,
  "markdown": icon_SiMarkdown_737373,
  "mikan": icon_SiMikanani_fda143,
  "nas": icon_SiSynology_b5b5b6,
  "nas tool": icon_SiNastool_2196f3,
  "nas-tools": icon_SiNastool_2196f3,
  "nastool": icon_SiNastool_2196f3,
  "proxmox": icon_SiProxmox_e57000,
  "pve": icon_SiProxmox_e57000,
  "qbit": icon_SiQbittorrent_2f67ba,
  "qbittorrent": icon_SiQbittorrent_2f67ba,
  "rss": icon_SiRss_ff6600,
  "safeline": icon_SiSafeline_79ba49,
  "synology": icon_SiSynology_b5b5b6,
  "tophub": icon_SiTophub_ff5722,
  "trilium": icon_SiTrilium_6eaa5e,
  "uptime": icon_SiUptimekuma_5cdd8b,
  "uptime kuma": icon_SiUptimekuma_5cdd8b,
  "uptimekuma": icon_SiUptimekuma_5cdd8b,
  "waf": icon_SiSafeline_79ba49,
}
